# Generated by Django 4.0.6 on 2022-07-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Actechnicianservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ambulanceserviceinlahore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Batteryreplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Brakerepairreplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cardetailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carpenteryservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carpetceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Carwash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
                ('Subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Depoxyflooring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Electricalservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Epoxyflooring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Exteriorninterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Falseceiling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flooringsolutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fumigationservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gardeningservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Generatorservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Glasscoatingservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Glazingservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Graphiccoating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Headlightrepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heatproofing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Masonservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Oilchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pabxsystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paintservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plantservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plumbingservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Skills', models.CharField(max_length=200)),
                ('Phoneno', models.CharField(max_length=13)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Address', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sofacleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Surveillancesystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Waterproofing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Watertankcleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phoneno', models.TextField()),
                ('Message', models.TextField()),
            ],
        ),
    ]
